### ISSUE TITLE
Info blurb

### ISSUE THREAD

**Issue by andrew-vancil** [geomarker-io/h2_shiny_map#1]
I currently have the app live at https://andrew-vancil.shinyapps.io/h2_shiny_map/ with the tweaks we talked about yesterday.

At the bottom is the space for an info blurb. If you want, you can edit line 51 in app.r or you can just write it here and I'll paste it in and redeploy. Also let me know if you have any other tweaks or adjustments!

@cole-brokamp

**Comment by cole-brokamp** [comment]
Thanks, I will add blurb soon.  Here's a couple notes:

- make the fill a little less transparent
- remove slope from legend
- add units and title to legend that are specific for each metric
- color legend doesn't seem to work for 95% CI coverage?

**Comment by andrew-vancil** [comment]
I've got an updated version redeployed. I think the CI coverage map is working, but the all and annual resolutions are 100% across the board - there's some variation at the other resolutions. Was there something else that seemed wonky? Let me know if I made the opacity a little too dark now, I went back and forth trying to dial it in

**Comment by cole-brokamp** [comment]
Can we set it up so that the units for the legend only show up once in parenthesis after the legend title, rather than for each number in the legend?

Also, I think we can remove the main title for the selector box and just keep the two subtitles "Temporal Resolution" and "Performance Metric"
