### ISSUE TITLE
add layer of points that illustrates where EPA sampling stations are

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/h2_shiny_map#3]

**Comment by andrew-vancil** [comment]
I've finished up getting the coloring added to the aqs monitor hexes. 

I unfortunately didn't think to do this in a separate branch to do a pull request, so let me know if you want me to show you the map before I push to shinyapps.io

**Comment by cole-brokamp** [comment]
that's ok.  can you go ahead and push?
